### ISSUE TITLE
[BUG] Back button does not work when error 403 popup message is shown

### ISSUE THREAD

**Issue by qexat** [xornet-cloud/Client#1]
## Environment

- OS: `Linux/Ubuntu 21.10` (64 bits)
- Browser: `Google Chrome v96.0.4664.9` (dev, 64 bits)
- Xornet version: [`current`](https://xornet.cloud) (18 12 2021)
- Reproducibility rate: `always` (100%)

## Steps to reproduce

1. Go to the [dashboard](https://xornet.cloud/dashboard/machines/all)
2. Click on any machine you don't own
3. When the error 403 message pops up on the top, click on the back button

## Expected Result

It should go back to the dashboard with all machines.

## Actual Result

Nothing happens, until you click on the back button once the pop up has disappeared.

**Comment by Geoxor** [comment]
bruh outdated issue that doesn't even belong to this repo
