### ISSUE TITLE
Barely anything is readable on the light theme

### ISSUE THREAD

**Issue by Geoxor** [xornet-cloud/Client#27]

**Comment by otiskujawa** [comment]
`th {
  @apply text-white text-left text-opacity-50 font-normal px-4 py-1.5 ;
}`
in Client/packages/vue/src/components/base/BaseTable.vue

This override the text color in the light theme.

Text color on web version in DevTools:
![image](https://user-images.githubusercontent.com/49094075/150653859-71c5692d-6c08-46c2-84e3-2872cf0b1bbb.png)

text-white probably destroys dashboard in light theme

**Comment by Geoxor** [comment]
oh i already fixed the text on https://github.com/xornet-cloud/Client/commit/b7ba4f6517705ccebb90bd7f15a02222e862c573
looks like this now

![image](https://user-images.githubusercontent.com/34042825/150672916-e29184d4-5fcf-4c36-a651-b36fd477ab7c.png)

should make more issues for anything else that has problems regarding this
