### ISSUE TITLE
The logout button and skull in the confirmation window are not visible in light mode

### ISSUE THREAD

**Issue by otiskujawa** [xornet-cloud/Client#33]
![image](https://user-images.githubusercontent.com/49094075/150675133-57a22c58-f1ca-413f-affd-71d14bb3080c.png)
![image](https://user-images.githubusercontent.com/49094075/150675219-1518a97b-fdc9-4bc4-9075-583de6917322.png)

The logout button and skull in the confirmation window are not visible in light mode
Tooltip is too low btw

![image](https://user-images.githubusercontent.com/49094075/150675230-4c3c7802-95bb-4688-bf1a-310bb1a317c0.png)
![image](https://user-images.githubusercontent.com/49094075/150675236-a02090fe-f22d-4a48-bac6-a08688b97cf7.png)

Windows 10 Chrome

**Comment by Geoxor** [comment]
yeah the tooltips are in the shit because they don't recompute their position when stuff layout shifts, im not sure how to fix that yet @Bluskript

time to fix the skull 💀
