### ISSUE TITLE
Add profile to machine page

### ISSUE THREAD

**Issue by otiskujawa** [xornet-cloud/Client#46]
**User name and profile would be a good addition to machine page**

It is not known who this machine belongs to:
![image](https://user-images.githubusercontent.com/49094075/154534254-e1658a1c-7e37-42c5-a676-a929d3834cff.png)
How it might look like:
![image](https://user-images.githubusercontent.com/49094075/154535723-a597d1fd-e4d7-4eab-a634-252aae6e2b57.png)

**Comment by Geoxor** [comment]
ill do that
