### ISSUE TITLE
Version info on status bar?

### ISSUE THREAD

**Issue by otiskujawa** [xornet-cloud/Client#48]
**Is your feature request related to a problem? Please describe.**
It would be cool to add the version info to the status bar.

**Describe the solution you'd like**
Version number on status bar.

**Describe alternatives you've considered**
Version number in options, logout menu or somewhere else.

**Additional context**
Option 1:
![image](https://user-images.githubusercontent.com/49094075/154820599-b06d27b1-bbe9-4563-af20-a92105727f48.png)
Option 2:
![image](https://user-images.githubusercontent.com/49094075/154820773-70181fc1-9af9-46aa-9bc5-0a85c5894a48.png)

Btw
Why is there only 1 info in debug status bar?
![image](https://user-images.githubusercontent.com/49094075/154820617-05b50ee4-9aaa-46b9-83cb-34593792ba0e.png)

**Comment by Geoxor** [comment]
closing this because the status bar no longer exists (for now)
