### ISSUE TITLE
Fix non-appearing columns

### ISSUE THREAD

**Issue by otiskujawa** [xornet-cloud/Client#50]
**Describe the bug**
Some columns do not appear sometimes.

**To Reproduce**
1. Enable CPU Average Speed column/Every column

**Screenshots, gifs, other media**
![image](https://user-images.githubusercontent.com/49094075/156892044-690e1663-abfc-4f4c-aef8-0a3a4f02b007.png)
![image](https://user-images.githubusercontent.com/49094075/156892064-a1e017b4-5726-4490-9cd2-823c9e370670.png)
![image](https://user-images.githubusercontent.com/49094075/156892086-1a48b623-18d3-4ce4-87bc-ff539747a4b0.png)
![image](https://user-images.githubusercontent.com/49094075/156892102-78c6bb1f-fd5a-41b5-9654-96da193c2c23.png)

**Environment (please complete the following information):**
 - OS (On which the bug occurs): Windows 10 (Chrome + client), Android
 - OS (On which everything works): POP_OS, Ubuntu
 - Does the bug happen with extensions disabled (if using browser): Idk but it also occurs in the client and on the phone

**Additional context**
Refreshing didn't change anything.
The problem can be solved by installing linux :tro:

**Comment by poixone** [comment]
ur father

**Comment by Geoxor** [comment]
this is a beta bug because you still have the old localStorage from the early versions, just delete the "columns" object or all of your localStorage (u can do that by logging out and logging in again)
