### ISSUE TITLE
Height of the <Avatar> component inconsistent on different aspect ratios

### ISSUE THREAD

**Issue by vapronva** [xornet-cloud/Client#56]
### Describe the Bug

The height of a given user avatar in `MachineList` is incredibly large.

### Steps to Reproduce

1. Log into [xornet.cloud](https://xornet.cloud), open [dashboard with machines](https://xornet.cloud/#/dashboard/machines)
2. Open the given page in a Safari browser and in a, for instance, Firefox
3. Enjoy the view of comically large and stretched avatars!

### Expected Behavior
User avatar of a machine in [`MachineList`](https://github.com/xornet-cloud/Client/blob/main/packages/vue/src/components/MachineList.vue) should be a circle of a reasonable size.

### Screenshots, GIFs, Other Media

- [troll screen recording *(earrape warning)*](https://live.vapronva.pw/73944d6c-d888-477b-9ce3-f2da6fc4f856)
- dashboard in safari without modifications *[screenshot 1]*
- dashboard in firefox without modifications *[screenshot 2]*
- dashboard in safari (ios) without modifications *[screenshot 3]*
- dashboard in safari with modified `h-full` css class *[screenshot 4]*

![dashboard in safari without modifications](https://static.lisour.vapronva.pw/issues-git/xornet-client/images/screenshot-2022_03_17-at-08_48_02.png)
![dashboard in firefox without modifications](https://static.lisour.vapronva.pw/issues-git/xornet-client/images/screenshot-2022_03_17-at-08_49_09.png)
![dashboard in safari (ios) without modifications](https://static.lisour.vapronva.pw/issues-git/xornet-client/images/screenshot-2022_03_17-at-18_14_34.png)
![dashboard in safari with modified h-full css class](https://static.lisour.vapronva.pw/issues-git/xornet-client/images/screenshot-2022_03_17-at-08_48_17.png)

#### Computer

- OS: macOS 12.2.1
- Browser **1**: Safari (version 15.3)
- Browser **2**: Firefox (version 98.0.1)
- Does the bug happen with extensions disabled: yes

#### Phone

- OS: iOS 15.1
- Browser **1**: Safari (version UNKNW)
- Does the bug happen with extensions disabled: yes

### Additional Context

The issue was non-existent before yesterday commits (either [this](https://github.com/xornet-cloud/Client/commit/cefcad1da0ca5b35c30095905c4fa8257fc32059) or [this](https://github.com/xornet-cloud/Client/commit/7a9e204e8bedb173d5de16fe62b3ace73eaf07b6)).

### Possible Resolution

Remove `h-full` from avatar image in `MachineList` (idk, that's weird, but it works).

**Comment by Geoxor** [comment]
LMFAO ill fix this

**Comment by Geoxor** [comment]
Note to self: fix avatar component so different aspect ratios don't fuck it

![image](https://user-images.githubusercontent.com/34042825/159192207-7960eaf5-b36e-442a-af1f-dc0b58624ce5.png)

**Comment by Geoxor** [comment]
this is starting to become a lot more bullshit than i expected

**Comment by Geoxor** [comment]
not sure if this is still a bug or not

**Comment by vapronva** [comment]
> not sure if this is still a bug or not

yep, it seems to be working fine (tested on ios and macos in the same safari versions).
and all of other new features seem to work just alright. i guess, will close the issue now!
